---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dse-cluster
  labels:
    cassandra.datastax.com/cluster: cluster-name
spec:
  selector:
    matchLabels:
      cassandra.datastax.com/cluster: cluster-name
  targetLabels:
  - cassandra.datastax.com/cluster
  - cassandra.datastax.com/datacenter
  endpoints:
  - targetPort: 9103
    scheme: http
    path: /metrics
    scrapeTimeout: 15s
    interval: 15s
    metricRelabelings: []
