name: Package Kubernetes Resources

on:
  push:
    branches: 
      - master
      - k8s-packaging
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd k8s-build
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          cd k8s-build
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Build k8s Resources and commit
        run: |
          k8s-build/bin/clean.py
          k8s-build/bin/build.py
          
          git status
          git diff --no-ext-diff --quiet --exit-code
          if [ $? -ne 0 ] then
            git status
          else
            git diff
          fi
